algoritmo "semnome"
//Cos( expressão) - Retorna o co-seno do ângulo (em radianos) representado por expressão
//Sen( expressão) - Retorna o seno do ângulo (em radianos) representado por expressão.
//Tan( expressão) - Retorna a tangente do ângulo (em radianos) representado por expressão.
var
AB,senA:real
inicio

AB<-(((180-100)^2)+((275-200)^2))^(1/2)
escreval("AB=",AB:5:2)

senA<-(sen(30)*100)/109
escreval("senA=",senA:5:2)


fimalgoritmo
